# Generated by Django 4.0.3 on 2022-03-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_user_room_host_message_room_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
